package com.example.hoply.db;

import static androidx.room.ForeignKey.CASCADE;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

@Entity(tableName = "posts",
        foreignKeys = {@ForeignKey(
                entity = HoplyUser.class,
                parentColumns = "id",
                childColumns = "user_id",
                onDelete = CASCADE)})
public class HoplyPost {

    @PrimaryKey()
    @ColumnInfo(name = "id")
    @NonNull
    private Integer postId;

    @NonNull
    @ColumnInfo(name = "user_id", index = true)
    private String userId;

    @NonNull
    @ColumnInfo(name = "content")
    private String content;

    @ColumnInfo(name = "stamp")
    private long timestamp;

    /**
     * Constructor for creating posts based on the given attributes with autogenerated timestamp
     * @param postId - Should be a unique identifier for this post
     * @param userId - the userId of the user who created the post
     * @param content - the text contained in the post
     */
    public HoplyPost(@NonNull Integer postId, @NonNull String userId, @NonNull String content){
        this.postId = postId;
        this.userId = userId;
        this.content = content;
        this.timestamp = System.currentTimeMillis();
    }

    /**
     * Constructor for creating posts based on the given attributes
     * @param postId - The unique identifier for this post
     * @param userId - the userId of the user who created the post
     * @param content - the text contained in the post
     * @param timeMillis - the time of which the post was created entered manually in milliseconds
     */
    public HoplyPost(@NonNull Integer postId, @NonNull String userId, @NonNull String content, long timeMillis){
        this.postId = postId;
        this.userId = userId;
        this.content = content;
        this.timestamp = timeMillis;
    }

    /**
     * Returns the id of this post
     * @return this posts id
     */
    @NonNull
    public Integer getPostId() {
        return postId;
    }

    /**
     * Returns the id of the user who made this post
     * @return the userId of the user who made the post
     */
    @NonNull
    public String getUserId() {
        return userId;
    }

    /**
     * Returns the content contained in this post
     * @return this posts content
     */
    @NonNull
    public String getContent() {
        return content;
    }

    /**
     * Returns the timestamp of which this post was created
     * @return long describing when the post was created
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the postId of this post
     * @param postId - what should be a unique identifier for this post
     */
    public void setPostId(@NonNull Integer postId) {
        this.postId = postId;
    }

    /**
     * Sets the content of this post
     * @param content - the text contained within this post
     */
    public void setContent(@NonNull String content) {
        this.content = content;
    }

    /**
     * Sets the timestamp of this post
     * @param timestamp - the time of which the post was created entered manually in milliseconds
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns a new comment which is an exact copy of this post
     * @return an exact copy of this post
     */
    public HoplyPost copy() {
        return (new HoplyPost(this.postId, this.userId, this.content, this.timestamp));
    }
}